### ISSUE TITLE
which train set used? Tusimple or CULane?

### ISSUE THREAD

**Issue by lllkjh** [Jade999/caffe_lane_detection#4]
which train set was this caffe model based on? looks like it was trained using CULane?

**Comment by s95huang** [comment]
Based on the image size, I think he used CULane
        img_w, img_h = 1640, 590
        row_anchor = culane_row_anchor

**Comment by lllkjh** [comment]
> Based on the image size, I think he used CULane
> img_w, img_h = 1640, 590
> row_anchor = culane_row_anchor

thx, i checked the relative params. u r correct.
